import "@radix-ui/themes/styles.css";
import './theme-config.css'
import './globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
// import NavBar from "./NavBar";
import Sidebar from "./Sidebar";
import MainScreen from "./MainScreen";


const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter',
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme appearance="light" accentColor="sky" radius="large">
         <Sidebar />
         <MainScreen />
          <main className="">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
